# Generated by Django 4.0.1 on 2022-03-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0007_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
