# Generated by Django 4.0.1 on 2022-03-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0008_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipe'),
        ),
    ]
