# Generated by Django 4.0.1 on 2022-03-25 16:08

from django.db import migrations, models
import meal_planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0011_alter_recipe_photo_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=meal_planner.models.upload_to, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to=meal_planner.models.upload_to, verbose_name='Photo'),
        ),
    ]
