# Generated by Django 4.0.1 on 2022-04-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0016_ingredient_user_meal_user_recipe_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
    ]
