# Generated by Django 4.0.1 on 2022-04-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0017_remove_meal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='user',
        ),
    ]
