# Generated by Django 4.0.1 on 2022-04-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0018_remove_recipeingredient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='meal_planner.plan'),
        ),
    ]
