# Generated by Django 4.0.1 on 2022-04-08 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0019_user_active_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='meal_planner.plan'),
        ),
    ]
